apiVersion: v1
kind: Service
metadata:
  name: springdockkube-service
spec:
  type: LoadBalancer
  selector:
    app: springdockkube
  ports:
    - protocol: TCP
      port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 1122
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      